### PR TITLE
Allow callbacks to be restored not just during training

### LINKED ISSUE #20137: Support restoring callbacks' status when predicting
### Description & Motivation

I implemented EMA using Callback. However, when predicting, the callback's weight isn't loaded back 

### Pitch

remove the condition at: https://github.com/Lightning-AI/pytorch-lightning/blob/f5d82504da252a255df268bd2bb99bf3f2886d27/src/lightning/pytorch/trainer/connectors/checkpoint_connector.py#L400

### Alternatives

_No response_

### Additional context

_No response_

cc @borda

### PR DESCRIPTION
**Pull request by chualanagit**
## What does this PR do?

Fixes #20137

<details>
  <summary><b>Before submitting</b></summary>

- [x] Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

----
📚 Documentation preview 📚: https://pytorch-lightning--20403.org.readthedocs.build/en/20403/

### CODE REVIEW

**Comment by lantiga** [comment]
hey @chualanagit thanks for the contribution!

looks reasonable to me, can you please add an example of usage to the linked issue?

**Comment by chualanagit** [comment]
> hey @chualanagit thanks for the contribution!
> 
> looks reasonable to me, can you please add an example of usage to the linked issue?

will do, thanks for the review, I'm still doing some testing, will get back to you all here soon!

**Comment by chualanagit** [comment]
Can someone shed some light on this `Probot / required-jobs (pull_request) ` timeout

**Comment by lantiga** [comment]
Looks good, merging! Thanks for the PR @chualanagit

**Pull request merged**
