### PR TITLE
Fix resetting epoch loop restarting flag in LearningRateFinder

### PR DESCRIPTION
**Pull request by clumsy**
## What does this PR do?
`lr_finder` does not reset `fit_loop.epoch_loop.restarting` to `False` which causes the validation check to trigger validation on the first `advance()` call because of [this check](https://github.com/Lightning-AI/pytorch-lightning/blob/b9680a364da4e875b237ec3c03e67a9c32ef475b/src/lightning/pytorch/loops/training_epoch_loop.py#L199).

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

----
📚 Documentation preview 📚: https://pytorch-lightning--19819.org.readthedocs.build/en/19819/

### CODE REVIEW

**Comment by clumsy** [comment]
Could you please check this fix @awaelchli , @carmocca ?

**Review by awaelchli — APPROVED** [review]

**Comment by awaelchli** [comment]
Thank you for the fix @clumsy, very nice!
It looks like the batch size finder would need the same fix as well. Are you interested to investigate it as well?

**Comment by clumsy** [comment]
Interesting, batch_size_finder actually worked for me but I can check and make the change, sure.

The was a more critical bug for LR finder, I'm afraid, @awaelchli: https://github.com/Lightning-AI/pytorch-lightning/pull/19814

**Comment by clumsy** [comment]
This flag reset is seem to be in place for batch_size_finder [here](https://github.com/Lightning-AI/pytorch-lightning/blob/06ea3a05716a6d1f4a96cfb25021accdd18d8146/src/lightning/pytorch/tuner/batch_size_scaling.py#L158), @awaelchli

**Pull request merged**
