### PR TITLE
Call `prepare_data()` after `setup_environment()` for XLA

### LINKED ISSUE #19174: prepare_data() not called correctly on XLA
### Bug description

When running on AWS [Trainium](https://aws.amazon.com/machine-learning/trainium/)  (TPU like device), I am seeing an issue where the [prepare_data](https://github.com/Lightning-AI/pytorch-lightning/blob/7bd75778a69343d5a31276b564463d870fb9cb47/src/lightning/pytorch/trainer/connectors/data_connector.py#L100) hook is called on all the ranks causing a crash.

This occurs due to the fact that the `local_rank/global_rank` is only set correctly after [set_environment()](https://github.com/Lightning-AI/pytorch-lightning/blob/7bd75778a69343d5a31276b564463d870fb9cb47/src/lightning/pytorch/trainer/trainer.py#L946) is called.

The issue was fixed after moving [prepare_data()](https://github.com/Lightning-AI/pytorch-lightning/blob/7bd75778a69343d5a31276b564463d870fb9cb47/src/lightning/pytorch/trainer/trainer.py#L940)  after [set_environment()](https://github.com/Lightning-AI/pytorch-lightning/blob/7bd75778a69343d5a31276b564463d870fb9cb47/src/lightning/pytorch/trainer/trainer.py#L946)



### What version are you seeing the problem on?

v2.1.2

### How to reproduce the bug
Training script:
```
import torch
from pytorch_lightning import LightningDataModule, LightningModule, Trainer
from pytorch_lightning.strategies.xla import XLAStrategy
from lightning_fabric.plugins.environments import TorchElasticEnvironment
from torch.utils.data import DataLoader, Dataset

class CustomStrategy(XLAStrategy):
    def __init__(
        self,
        accelerator=None,
        parallel_devices=None,
        checkpoint_io=None,
        precision_plugin=None,
        debug=False,
        sync_module_states=True,
        **_,
    ) -> None:
        super(XLAStrategy, self).__init__(
            accelerator=accelerator,
            parallel_devices=parallel_devices,
            cluster_environment=TorchElasticEnvironment(),
            checkpoint_io=checkpoint_io,
            precision_plugin=precision_plugin,
            start_method="popen",
        )
        self.debug = debug
        self._launched = False
        self._sync_module_states = sync_module_states

    def setup_distributed(self) -> None:
        # Call DDP's setup_distributed
        super(XLAStrategy, self).setup_distributed()
        self._launched = True

    def _get_process_group_backend(self) -> str:
        return 'xla'

    def _configure_launcher(self) -> None:
        """
        Use DDP's launcher
        """
        super(XLAStrategy, self)._configure_launcher()

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
       self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

class BoringDataModule(LightningDataModule):
    def __init__(self):
        super().__init__()

    def prepare_data(self):
        print("I'm running on rank", self.trainer.global_rank)

    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 64), batch_size=2)

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        return self(batch).sum()

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    model = BoringModel()
    trainer = Trainer(max_epochs=1, devices=32, accelerator="tpu", strategy=CustomStrategy())
    trainer.fit(model, datamodule=BoringDataModule())


if __name__ == "__main__":
    run()                                                                                                                                                                                                                           
```

Launch command:

```
torchrun --nproc_per_node=32 <train script>
```

### Error messages and logs
I see 32 calls to prepare_data()
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
I'm running on rank 0
I'm running on rank 0
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 29, MEMBER: 30/32
Initializing distributed: GLOBAL_RANK: 12, MEMBER: 13/32
Initializing distributed: GLOBAL_RANK: 19, MEMBER: 20/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 27, MEMBER: 28/32
I'm running on rank 0
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 17, MEMBER: 18/32
Initializing distributed: GLOBAL_RANK: 26, MEMBER: 27/32
GPU available: False, used: False
TPU available: True, using: 32 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 30, MEMBER: 31/32
I'm running on rank I'm running on rank0 
0
Initializing distributed: GLOBAL_RANK: 16, MEMBER: 17/32
Initializing distributed: GLOBAL_RANK: 13, MEMBER: 14/32
I'm running on rankI'm running on rank  00

I'm running on rank 0I'm running on rank
I'm running on rank  00

I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 25, MEMBER: 26/32
Initializing distributed: GLOBAL_RANK: 11, MEMBER: 12/32
Initializing distributed: GLOBAL_RANK: 6, MEMBER: 7/32
Initializing distributed: GLOBAL_RANK: 22, MEMBER: 23/32
Initializing distributed: GLOBAL_RANK: 9, MEMBER: 10/32
Initializing distributed: GLOBAL_RANK: 8, MEMBER: 9/32
I'm running on rank 0
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 10, MEMBER: 11/32
Initializing distributed: GLOBAL_RANK: 24, MEMBER: 25/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 31, MEMBER: 32/32
I'm running on rank 0
I'm running on rank 0
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/32
Initializing distributed: GLOBAL_RANK: 15, MEMBER: 16/32
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 14, MEMBER: 15/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 18, MEMBER: 19/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/32
I'm running on rank 0
I'm running on rank 0
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/32
Initializing distributed: GLOBAL_RANK: 23, MEMBER: 24/32
Initializing distributed: GLOBAL_RANK: 20, MEMBER: 21/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 5, MEMBER: 6/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 4, MEMBER: 5/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 28, MEMBER: 29/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 21, MEMBER: 22/32
I'm running on rank 0
Initializing distributed: GLOBAL_RANK: 7, MEMBER: 8/32
----------------------------------------------------------------------------------------------------
distributed_backend=xla
All distributed processes registered. Starting with 32 processes
----------------------------------------------------------------------------------------------------
```


### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
#- PyTorch Lightning Version (e.g., 1.5.0):  2.1.2
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):  2.0.1
#- Python version (e.g., 3.9):  3.10.12
#- OS (e.g., Linux):  Linux
#- CUDA/cuDNN version: N/A
#- GPU models and configuration:  AWS Trainium. Single Node
#- How you installed Lightning(`conda`, `pip`, source):  pip
#- Running environment of LightningApp (e.g. local, cloud):  local
```

</details>


### More info
With the fix, I am only seeing `prepare_data()` called once

```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Initializing distributed: GLOBAL_RANK: 24, MEMBER: 25/32
Initializing distributed: GLOBAL_RANK: 8, MEMBER: 9/32
GPU available: False, used: False
TPU available: True, using: 32 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 6, MEMBER: 7/32
Initializing distributed: GLOBAL_RANK: 23, MEMBER: 24/32
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/32
Initializing distributed: GLOBAL_RANK: 16, MEMBER: 17/32
Initializing distributed: GLOBAL_RANK: 27, MEMBER: 28/32
Initializing distributed: GLOBAL_RANK: 10, MEMBER: 11/32
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/32
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/32
Initializing distributed: GLOBAL_RANK: 13, MEMBER: 14/32
Initializing distributed: GLOBAL_RANK: 12, MEMBER: 13/32
Initializing distributed: GLOBAL_RANK: 14, MEMBER: 15/32
Initializing distributed: GLOBAL_RANK: 19, MEMBER: 20/32
Initializing distributed: GLOBAL_RANK: 28, MEMBER: 29/32
Initializing distributed: GLOBAL_RANK: 31, MEMBER: 32/32
Initializing distributed: GLOBAL_RANK: 29, MEMBER: 30/32
Initializing distributed: GLOBAL_RANK: 22, MEMBER: 23/32
Initializing distributed: GLOBAL_RANK: 20, MEMBER: 21/32
Initializing distributed: GLOBAL_RANK: 17, MEMBER: 18/32
Initializing distributed: GLOBAL_RANK: 11, MEMBER: 12/32
Initializing distributed: GLOBAL_RANK: 25, MEMBER: 26/32
Initializing distributed: GLOBAL_RANK: 4, MEMBER: 5/32
Initializing distributed: GLOBAL_RANK: 5, MEMBER: 6/32
Initializing distributed: GLOBAL_RANK: 7, MEMBER: 8/32
Initializing distributed: GLOBAL_RANK: 15, MEMBER: 16/32
Initializing distributed: GLOBAL_RANK: 21, MEMBER: 22/32
Initializing distributed: GLOBAL_RANK: 18, MEMBER: 19/32
Initializing distributed: GLOBAL_RANK: 26, MEMBER: 27/32
Initializing distributed: GLOBAL_RANK: 9, MEMBER: 10/32
Initializing distributed: GLOBAL_RANK: 30, MEMBER: 31/32
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/32
----------------------------------------------------------------------------------------------------
distributed_backend=xla
All distributed processes registered. Starting with 32 processes
----------------------------------------------------------------------------------------------------

I'm running on rank 0

```

cc @carmocca @JackCaoG @Liyang90 @gkroiz

### PR DESCRIPTION
**Pull request by jerrymannil**
## What does this PR do?

Fixes #19174

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

----
📚 Documentation preview 📚: https://pytorch-lightning--19181.org.readthedocs.build/en/19181/

### CODE REVIEW

**Comment by jerrymannil** [comment]
@awaelchli  Can you look ?

**Comment by awaelchli** [comment]
@jerrymannil In principle this change would be ok. It's a bit more work though, because so far the assumption was that the DeepSpeed strategy can call the `train_dataloader()` method to grab the batch size for its configuration. But now that prepare_data has moved, it would no longer be valid for DeepSpeed to call it this early. So that part of the DeepSpeed strategy implementation will have to be refactored too. I will look into it when I have some spare time.

**Comment by awaelchli** [comment]
For context, this is the call that DeepSpeed makes:
https://github.com/Lightning-AI/pytorch-lightning/blob/6d47bf1fac5a1029ae2662d12db9d4236608f645/src/lightning/pytorch/strategies/deepspeed.py#L654C17-L654C33

Up the call stack, you can see that this formatting of the config happens in `setup_environment()`. 
https://github.com/Lightning-AI/pytorch-lightning/blob/6d47bf1fac5a1029ae2662d12db9d4236608f645/src/lightning/pytorch/strategies/deepspeed.py#L343C8-L343C8

Now that `prepare_data()` runs after `setup_environment()`, the validation and configuration of the config would have to move as well. Probably to the `setup()` method.

**Comment by jerrymannil** [comment]
@awaelchli 
Can I update the fix to be XLA specific for now ?
Once deepspeed is fixed, we can remove XLA check.

**Comment by jerrymannil** [comment]
> Can I update the fix to be XLA specific for now ?
> Once deepspeed is fixed, we can remove XLA check.

@awaelchli 
Pushed a new commit limiting the the fix for XLA

**Comment by awaelchli** [comment]
@jerrymannil I made this PR #19209 to rework the DeepSpeed logic.

**Review by awaelchli — COMMENTED** [review]
The change LGTM, thanks!

We will need to extend the prepare-data test(s) for XLA, but first I need to understand why TPU tests were skipped on this PR. @carmocca @Borda is it because the PR comes from a fork?

**Review by jerrymannil — COMMENTED** [review]
LGTM.  Thanks.

**Comment by carmocca** [comment]
The TPU tests now require a label to run (added), however, they are currently non-functional. We need to drop XRT support and fix a PjRT test.

I would agree with merging this anyways

**Comment by jerrymannil** [comment]
@awaelchli  Can we merge then ?

**Comment by carmocca** [comment]
Unfortunaterly not, this PR seems to be introducing this error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 92, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 245, in _run_thread_per_device
    replica_results = list(
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 238, in _thread_fn
    return fn()
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 341, in __call__
    self.fn(global_ordinal(), *self.args, **self.kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/launchers/xla.py", line 144, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/runner/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 942, in _run
    self.strategy.setup_environment()
  File "/home/runner/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/ddp.py", line 153, in setup_environment
    super().setup_environment()
  File "/home/runner/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/strategy.py", line 128, in setup_environment
    self.accelerator.setup_device(self.root_device)
  File "/home/runner/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/xla.py", line 109, in root_device
    raise RuntimeError("Accessing the XLA device before processes have spawned is not allowed.")
RuntimeError: Accessing the XLA device before processes have spawned is not allowed.
```

**Comment by awaelchli** [comment]
I wrote a comment about that here https://github.com/Lightning-AI/pytorch-lightning/pull/19232#discussion_r1447650508

**Review by awaelchli — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Comment by jerrymannil** [comment]
Thanks @awaelchli @carmocca

**Pull request merged**
