### PR TITLE
docs: added mathjax for rendering tex format as imgmath needs latex engine to run

### LINKED ISSUE #19633: Docs don't render LaTeX formulas
### 📚 Documentation

Hi! 

I was reading the document and found the equation display error. Here is the [link](https://lightning.ai/docs/pytorch/stable/notebooks/course_UvA-DL/03-initialization-and-optimization.html#Initialization) and the screenshot.

截屏2024-03-15 14 42 57

cc @borda

### PR DESCRIPTION
**Pull request by fnhirwa**
## What does this PR do?
Adding support to render latex math formulas, changing from `imgmath` to `mathjax` as `imgmath` requires latex engine to run.

part of #19633

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

----
📚 Documentation preview 📚: https://pytorch-lightning--19675.org.readthedocs.build/en/19675/

### CODE REVIEW

**Comment by Borda** [comment]
looks fine, just curious why this installed tex was not enough
https://github.com/Lightning-AI/pytorch-lightning/blob/51ad6bb8fe83184cea353b40141abccafd2b8823/.github/workflows/docs-build.yml#L93

**Comment by fnhirwa** [comment]
> looks fine, just curious why this installed tex was not enough
> 
> https://github.com/Lightning-AI/pytorch-lightning/blob/51ad6bb8fe83184cea353b40141abccafd2b8823/.github/workflows/docs-build.yml#L93

This makes sense I think the reason is that the docs workflow for tutorials repo this line got commented out and is a submodule for this project.

https://github.com/Lightning-AI/tutorials/blob/37e07988f981913721a613ac3ab40f53dcf6c9b2/.github/workflows/ci_docs.yml#L47

And was added to this commit 
https://github.com/Lightning-AI/tutorials/commit/1e046df7654f4ff034a711e5af77cd409adfccd5

I think we can consider using `mathjax` as it enables us to build docs locally without the need of a tex engine.

**Comment by fnhirwa** [comment]
> > looks fine, just curious why this installed tex was not enough
> > https://github.com/Lightning-AI/pytorch-lightning/blob/51ad6bb8fe83184cea353b40141abccafd2b8823/.github/workflows/docs-build.yml#L93
> 
> This makes sense I think the reason is that the docs for tutorials conf.py file didn't have an extension for latex formulas added and it is a submodule for this project.
> 
> I think we can consider using `mathjax` as it enables us to build docs locally without the need of a tex engine.

Sorry, my bad I checked and it is there I think the reason why this was failing we should add `imgmath_latex = 'latex'` configuration settings to the `conf.py` file.

But I would still recommend using `mathjax` over `imgmath` as for `imgmath` formulas are rendered as images and it won't bloat the docker image as we can fully get rid of the latext installation.

**Comment by Borda** [comment]
> I would still recommend using `mathjax` over `imgmath` as for `imgmath` formulas are rendered

That is completely fine with me :)

**Comment by fnhirwa** [comment]
This is sample for tex output when using mathjax
image

Output from Docs builds on PR

image

**Pull request merged**
