### PR TITLE
tests: changed mocked dir `tmpdir` to `tmp_path`

### LINKED ISSUE #16188: Replace `tmpdir` usage with `tmp_path` in our tests
### Outline & Motivation

`tmpdir` is considered legacy:

> The tmpdir and tmpdir_factory fixtures are similar to tmp_path and tmp_path_factory, but use/return legacy [py.path.local](https://py.readthedocs.io/en/latest/path.html) objects rather than standard [pathlib.Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path) objects.

(from https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures)

### Pitch

Run pytest with `pytest -p no:legacypath` as the link above suggests and replace all occurrences.

This can be added in https://github.com/Lightning-AI/lightning/blob/94e6d52b7e2f2a9ffc21f7e11e087808666fe710/setup.cfg#L28-L32

```diff
 addopts =
     --strict-markers
     --doctest-modules
     --color=yes
     --disable-pytest-warnings
     --ignore=legacy/checkpoints
+    -p no:legacypath
```

Replace all `tmpdir` usages

### Additional context

_No response_

cc @borda

### PR DESCRIPTION
**Pull request by Aditi840**
## What does this PR do?

Fixes #16188

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

### CODE REVIEW

**Review by Borda — APPROVED** [review]
just pushed minor simplification based on the fact `tmp_path` is already `PosixPath` but there can be cases where we may convert it to a string...

ref: https://www.freecodecamp.org/news/how-to-use-pathlib-module-in-python/

**Comment by Aditi840** [comment]
@Borda, do I need to change some more files or this much is ok.

**Comment by Aditi840** [comment]
@Borda please answer, do I need to change some more files or this much is ok.

**Comment by Borda** [comment]
> @Borda please answer, do I need to change some more files or this much is ok.

pls check the failing tests

**Comment by Aditi840** [comment]
@Borda there is an error which says.This job will need to be re-run to merge your PR. If you do not have write access to the repository you can ask Lightning-AI/lai-frameworks to re-run it for you. If you have any other questions, you can reach out to carmocca for help.

**Comment by Borda** [comment]
> @Borda there is an error which says.This job will need to be re-run to merge your PR. If you do not have write access to the repository you can ask Lightning-AI/lai-frameworks to re-run it for you. If you have any other questions, you can reach out to carmocca for help.

I see many more failing, for example:
- https://github.com/Lightning-AI/lightning/actions/runs/5963502249/job/16176829106?pr=18382
- https://github.com/Lightning-AI/lightning/actions/runs/5963502251/job/16176831776?pr=18382
- https://github.com/Lightning-AI/lightning/actions/runs/5963502237/job/16176826628?pr=18382

**Comment by Aditi840** [comment]
@Borda  in first example, its saying type error an integer is required (got type str)  and AssertionError: assert '/tmp/pytest-of-runner/pytest-0/test_file_logger_no_name__0' == PosixPath('/tmp/pytest-of-runner/pytest-0/test_file_logger_no_name__0')                  In second example, AttributeError: 'PosixPath' object has no attribute 'write'
loggers/test_logger.py:337: AttributeError, AttributeError: 'PosixPath' object has no attribute 'listdir', AssertionError: assert '/tmp/pytest-of-runner/pytest-0/test_simple_profiler_with_none0/nonexisting' == PosixPath('/tmp/pytest-of-runner/pytest-0/test_simple_profiler_with_none0/nonexisting')
E        +  where '/tmp/pytest-of-runner/pytest-0/test_simple_profiler_with_none0/nonexisting' = <lightning.pytorch.trainer.trainer.Trainer object at 0x7fef0fa7a790>.log_dir
profilers/test_profiler.py:131: AssertionError, AttributeError: 'PosixPath' object has no attribute 'join', and so many assertion errors, In third example, AttributeError: 'PosixPath' object has no attribute 'join', E           AssertionError: expected call not found.
E           Expected: put('file', PosixPath('/tmp/pytest-of-runner/pytest-0/test_copier_copies_all_files0/.shared/123'))
E           Actual: put('file', '/tmp/pytest-of-runner/pytest-0/test_copier_copies_all_files0/.shared/123')

/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/unittest/mock.py:913: AssertionError, , and many more attribute errors

**Comment by awaelchli** [comment]
@Aditi840 I propose that we break this effort into smaller junks. As you can see, we can't just "find+replace" tmpdir with tmp_path, because they are not functionally equivalent in all cases. That means some tests will need a slight update in the code, so whoever works on this will have to look at each test failure individually and fix it. 

Since this requires a bit of work, and there are many occurrences, I suggest that we do it in smaller pieces. It will also reduce the chance of merge conflict and should make your life easier too. Let me know what you think.

**Comment by Aditi840** [comment]
@awaelchli Good Idea, let's spilt the work then.

**Comment by Borda** [comment]
> @Aditi840 I propose that we break this effort into smaller junks.

already suggested in the original issue so we can track it there: https://github.com/Lightning-AI/lightning/issues/16188#issuecomment-1691189400

**Comment by Aditi840** [comment]
@Borda , please tell me your slack id

**Comment by Aditi840** [comment]
@awaelchli, lets split it, and tell me what needs to be done by my side.

**Comment by Borda** [comment]
> @Borda , please tell me your slack id

You can find me as Jirka :)
I made a sample partial fix, so based on partitions in https://github.com/Lightning-AI/lightning/issues/16188#issuecomment-1691189400, I just chose a topic/folder and tried to apply changes...

1. chose one folder and create a draft PR (which can be almost empty) that we can link the issues
2. take it file by file and perform replacement
3. I would suggest each file change shall be one commit in the PR so it is easier to trace what changes are not compatible

**Pull request closed without merging**
