### PR TITLE
Patch jsonargparse for Python >= 3.12.8

### PR DESCRIPTION
**Pull request by lantiga**
## What does this PR do?

This PR is a temporary fix to https://github.com/omni-us/jsonargparse/issues/641
so that users are not impacted even prior to the upstream fix being released.

This undoes pinning introduced in #20476

----
📚 Documentation preview 📚: https://pytorch-lightning--20479.org.readthedocs.build/en/20479/

### CODE REVIEW

**Comment by adamjstewart** [comment]
Seems like this patch is actually causing things to break now that jsonargparse is updated? TorchGeo CI is not happy with the 2.5.0 release: https://github.com/microsoft/torchgeo/actions/runs/12438070046/job/34729248038?pr=2484

**Comment by lantiga** [comment]
hey @adamjstewart looking into this, will issue a post release that fixes this in the next few minutes

**Comment by lantiga** [comment]
ok so should we bump `jsonargparse >= 4.35.0`, or apply the patch conditionally? I'm thinking that we do the latter since `jsonargparse` is an extra so pinning it might not have an effect in practice. wdyt @adamjstewart ?

**Comment by adamjstewart** [comment]
My vote would be to remove the patch and allow users to use any version of jsonargparse. This is a bug in jsonargparse, not a bug in lightning. Let users complain to jsonargparse, and then let jsonargparse tell them to upgrade to newer jsonargparse if they want to use newer Python. Users on older Python can still use older jsonargparse with newer lightning, lightning has no problems with older jsonargparse.

**Pull request merged**
